BASE_URL = "https://app.wallstreetsurvivor.com"
TRANSACTION_ENDPOINT = "/account/gettransactions"
REFERER_TRANSACTION_ENDPOINT = "/account/transactionhistory"
REFERER_HEADERS_ENDPOINT = "/account/dashboardv2"
PARQUET_FILENAME = "transactions.parquet"