services:
  app:
    build: .
    container_name: scraper-api
    env_file:
      - .env
    environment:
      - CHROME_BINARY=/usr/bin/chromium
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data